version: '3.8'

services:
  frontend:
    # Build the frontend service
    build:
      context: ./frontend

    # Map host port 3000 to container port 3000
    ports:
      - "3000:3000"  

    #  Starts backend before frontend  
    depends_on:
      - backend 

  backend:
    # Build the backend service
    build:
      context: ./backend
    
    # Map host port 5000 to container port 5000
    ports:
      - "5000:5000"  